### ISSUE TITLE
Update dependencies on crates.io 

### ISSUE THREAD

**Issue by smrpn** [casbin-rs/actix-casbin-auth#31] opened 2021-05-05 01:49 UTC
actix-casbin-auth uses tokio 1.5.0, but the webpage on crates.io shows 0.2. - 
![Screenshot from 2021-05-05 07-12-18](https://user-images.githubusercontent.com/55808717/117089007-d61bfc00-ad71-11eb-8649-821fc2df1988.png)
Also few other dependencies like actix-rt also need to updated. Can this be manually done?

**Comment by PsiACE** [comment] 2021-05-05 02:22
This should be caused by `actix-web` , there is no good way for the time being

**Comment by smrpn** [comment] 2021-05-05 03:11
`actix-casbin-auth` uses `actix-web 4.0.0-beta.6`. The code is working fine. 
I had to use `actix-casbin-auth = { git = "https://github.com/casbin-rs/actix-casbin-auth", branch = "master" }` in the Cargo.toml of `actix-casbin`, because the tests were failing when downloaded from crates.io. Can this be used? (I'm asking if this is allowed as per the coding standards)

**Comment by PsiACE** [comment] 2021-05-05 04:10
Of course. But if you use github directly, you will be temporarily unable to release a new version to crates.io. It may require you to pay more attention to maintenance.

**Comment by hsluoyz** [comment] 2021-05-29 02:38
@hackerchai

**Comment by thespooler** [comment] 2022-03-21 00:54
Should be resolved by #33. actix-web 4.0 depends on actix-rt 2.7, that depends on tokio 1.13.

**Closed** 2022-03-21 09:23 UTC
Labels: enhancement
